### ISSUE TITLE
登陆模块

### ISSUE THREAD

**Issue by schaepher** [fzu2015/CourseManagement#14]
任务耗时估计： 3小时
耗时估计前提： 没有写过登陆模块，但有看过登陆模块的代码。有http开源框架可以使用，有示例代码可以参考。
任务内容：
  写出登陆逻辑。能够发送数据到指定服务器，并获取返回结果。与合作伙伴沟通数据传输内容。

**Comment by zhengshiyuan** [comment]
实际耗时：7.5小时
