### ISSUE TITLE
登陆界面（LoginActivity）

### ISSUE THREAD

**Issue by schaepher** [fzu2015/CourseManagement#20]
任务耗时估计：2小时
耗时估计假设：已经找好需要用到的Material Design库
任务内容：
1. 根据原型的登陆界面，做出大致符合Material Design标准的登陆界面即可。
2. 注意，原型显示的logo换成福大校徽logo。

**Comment by woshidasusu** [comment]
实际耗时：4.0小时
已完成，不过为了尝试各种第三方库提供的控件哪个效果好，硬是把找的开源库都试了下，结果浪费了大量时间。下次会注意。
