### ISSUE TITLE
文件选择界面（FileSelectActivity）

### ISSUE THREAD

**Issue by schaepher** [fzu2015/CourseManagement#21]
任务耗时估计：2小时
耗时估计前提：已经准备好一些要用到的开源库。
任务内容：
1. 文件选择界面为一个ListView。
2. ListView的项要有：图标，文件名。
3. 保持能扩展成：一个文件夹里的所有xls文件显示出来，且在这些文件的最前面，有一栏标签显示这个文件夹的路径。
`       不一定要做出来这个标签效果，但保证以后想要扩展这个效果时能够只修改很少的代码就能完成。当然，如果能快速做出来，可以现在就做。`
4. 左上角要有一个返回的按钮。

**Comment by woshidasusu** [comment]
已完成，实际用时1小时48分钟，标签的扩展没有实现。

**Comment by woshidasusu** [comment]
补充，上面的1小时48分钟为敲代码耗时，加上查资料，看Demo，总耗时>3.5小时
