### ISSUE TITLE
报课表查看界面（ExcelDisplayActivity）

### ISSUE THREAD

**Issue by schaepher** [fzu2015/CourseManagement#28]
任务耗时估计：3小时  
耗时估计前提：已经有实现该界面的思路，以及有相应的资料。  
任务内容：  
  1.报课表查看界面以Excel的形式展现，暂不用实现缩放，能左右上下滚动就行。  
  2.单击某一行之后，弹出一个修改框。将该行所有值展示出来。其中可以修改的三个数值为：起讫周序，任课教师，备注，其余不可修改。

**Comment by woshidasusu** [comment]
已完成，实际耗时，3.5小时。ListView实现缩放资料不多，暂时无法实现。
