### ISSUE TITLE
任务详情界面（TaskDetailActivity）

### ISSUE THREAD

**Issue by schaepher** [fzu2015/CourseManagement#31]
任务耗时估计：2小时
耗时估计前提：已有开源框架，之前写界面的经验
任务内容：
1.按照原型的院任务详情界面写出该界面。
2.导出表格的按钮可以做在右上角，也可以按照Material Design标准设计成浮动按钮（推荐）。
3.教学办、系负责人、教师三者的界面统一成一个，不用重复做。
4.暂不做教学办修改截止时间的功能。
5.报课表汇总可做成按钮。

**Comment by woshidasusu** [comment]
已完成，实际耗时3小时，包括解决同步项目后的冲突及编译问题
