### ISSUE TITLE
教师列表界面（TeacherListActivity）

### ISSUE THREAD

**Issue by schaepher** [fzu2015/CourseManagement#33]
任务耗时估计：4小时
耗时估计前提：有开源框架，但之前没有涉及到标签的使用
任务内容：
1.按照原型做出教师列表界面。
2.暂不做搜索功能。
3.添加教师的按钮可以做在右上角，也可以按照Material Design标准设计成浮动按钮（推荐）。
4.能够按照系进行分块，并添加标签。
5.这个功能可暂时不做：标签滑动到顶部时不消失，直到下一个系的标签顶上来。

**Comment by woshidasusu** [comment]
已完成，实际耗时大约4小时
