### ISSUE TITLE
登陆保存用户名

### ISSUE THREAD

**Issue by schaepher** [fzu2015/CourseManagement#38]
任务耗时估计：1小时
耗时估计前提：了解SharedPreferences的使用
任务内容：
1.点击登陆时，打开SharedPreferences并将用户名存入里面。
2.当打开登陆界面时，检查SharedPreferences是否有存了用户名。如果有，则自动输入到用户名框框内；如果没有，则不做操作。

**Comment by woshidasusu** [comment]
已完成，实际耗时5分钟（前一个任务需要复习了SharedPreferences的使用，趁热完成了此功能）
