### ISSUE TITLE
登陆时根据不同身份显示不同界面

### ISSUE THREAD

**Issue by schaepher** [fzu2015/CourseManagement#47]
任务耗时估计：1小时（此后皆不把学习时间算在内）
任务内容：
1. 登陆时有三种身份选择，选择不同的身份，进入的界面要根据身份的权限来选择。
2. 用同一个界面，根据不同身份屏蔽相应的控件。

**Comment by woshidasusu** [comment]
暂时完成教师身份登录对应的界面，由于服务器目前只提供两种身份登录，故教学办以及系负责人登录界面相同

**Comment by woshidasusu** [comment]
补充，完成时间20分钟（不包括复习数据存储的时间）
