### ISSUE TITLE
教师列表的添加按钮弹出选项

### ISSUE THREAD

**Issue by schaepher** [fzu2015/CourseManagement#56]
任务耗时估计：1小时
任务内容：
1. 点击添加按钮时，在按钮处弹出两个选项。一个“手动输入”，一个“从文件导入”。
2. 点击后跳转到对应的界面

**Comment by woshidasusu** [comment]
已完成，等待世源将文件管理器搞定后我再来合并解决冲突。实际耗时，敲代码15分钟+查资料1小时
